language: node_js
node_js:
  - "4.0"
install:
  - npm install
  - npm install -g gulp
script:
  - gulp --travis
  - bash ./deploy.sh
env:
  global:
  - GH_REF: github.com/CJSCommonPlatform/govuk_bootstrap.git
