language: node_js
node_js:
  - "4.0"
install:
  - npm install
  - npm install -g gulp
script:
#  - gulp html-lint # removed as it causing issues
  - gulp --travis
  - bash ./deploy.sh
env:
  global:
  - GH_REF: github.com/CJSCommonPlatform/govuk_bootstrap.git
  - secure: "dZEZ0URcCjEVWX1OSBKAXapB9hnkNTbDDQfngsHNPOPuWxe33IF8tJlG4aw7wywkZ017uzDC37Z0R9ONBk5EdBWgw0AX9+UW5KKRr5MMZkmWvmjM1aOGTh9V5kYBI6MP99iVMwYsiPKH7KzB/cliKIqUQU6660KfZE36xhdElzzKwPLwH/Lw24krqjXLjKZUvKE8qHSdPGM26HVSneHd2GYy7P0CO/ee7B+Hg/VRYdWsJxUOfrqhdLNoRNiIyoKZyLoY26hVx7Vq7LioIUblKBzRODpK4HZFKNm/vGw6ywbttntGXWpXgK/AUHB/vskE+kVQvE0/HoyuAkgplAyGPS2YvR8bHAxkJjkwqR2mu9mg8OJQJTvy2+R385XyUQXePcRmwq542WVqh4D6Yp4Btp5bo54hvYubS3PQVseH4NHOzSKkyX8ZIW2+Cy66bFnC7Qy5KlmhOoSFo/AF1yKmbC5oi4BlmEp9D0gfPq60Lw9kWzCeTcmjdto9U0F4gWkZ1uCuPmmwGoXJ2xt65Nwa7KognWYbTzqSq7QY3uPjywPlN8GgcW/XjEKEpARVFrAoP4X1HkVjQMPijglsJ0gjagh1BOq8T1ewdX6WnZHiLYOErag8wuzIl7rsSkxSwL+9Mu38bvygsxm4mwiOpeT6k6+aikyeDIr0eCEvn+Cr73Y="